#include QMK_KEYBOARD_H
#include "tominabox1.h"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

	[_BASE] = LAYOUT(
    KC_GESC, KC_Q, KC_W, KC_F, KC_P, KC_G, KC_J, KC_L, KC_U, KC_Y, KC_QUOTE, KC_BSPC,
    KC_CTLTB,  LGUI_T(KC_A), LALT_T(KC_R), LCTL_T(KC_S), LSFT_T(KC_T), TD(TD_DCAP), KC_H, RSFT_T(KC_N), RCTL_T(KC_E), RALT_T(KC_I), RGUI_T(KC_O),
    LCTL(KC_F12),   LT(_NAV, KC_Z),    KC_X,    KC_C,    KC_V,    KC_B,    KC_K,    KC_M, KC_COMM,  KC_DOT, KC_SLSH,
    LT(_NAV,KC_CAPS), KC_NAV_ENT, KC_NO, KC_NAV_ENT,  KC_NAV_ENT,  KC_NUM_SPC, KC_NO, KC_NUM_SPC, KC_NAV_ENT, KC_MPLY, KC_MNXT
	),

	[_NUM_SYM] = LAYOUT(
    KC_GRV,  KC_1,     KC_2,     KC_3,     KC_4,     KC_5,     KC_6,     KC_7,     KC_8,     KC_9,     KC_0, KC_BSPC,
    KC_BSLS, KC_EXLM,    KC_AT,  KC_HASH,   TD(TD_DLR_LP), KC_PERC, KC_CIRC, TD(TD_AMP_RP),  KC_ASTR,   KC_EQL, KC_MINS,
    LCTL(KC_F12),  KC_TRNS,  KC_LCBR,  KC_LBRC,  KC_LPRN,   KC_UNDS, KC_RPRN,  KC_RBRC,  KC_RCBR,  KC_DOT,  KC_SLSH,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, LWIN(LCTL(KC_LEFT)), LWIN(LCTL(KC_RIGHT))
	),

	[_NAV] = LAYOUT(
    KC_NO,  KC_F1,  KC_F2, KC_NO, KC_NO,  KC_NO, KC_NO,  KC_PGDN,    KC_UP,  KC_PGUP, KC_NO, TD(TD_RESET),
    KC_PIPE,KC_NO,  KC_NO,  KC_NO,  KC_NO,  KC_NO, KC_HOME,  KC_LEFT,  KC_DOWN,  KC_RGHT, KC_END,
    LCTL(KC_F12),    KC_TRNS,  KC_NO,  KC_NO,  KC_NO,  LCTL(KC_F12),    KC_NO,  KC_COMM,   KC_DOT,  KC_NO, KC_BSLS,
    KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, LWIN(LCTL(KC_LEFT)), LWIN(LCTL(KC_RIGHT))
	),

};
